name: Kiểm tra và build project   #Tên quy trình

on:
  push:
    branches: [ "main" ]   #Chạy khi push lên main

jobs:
  build_project:
    runs-on: ubuntu-latest   #Dùng máy ảo Ubuntu

    steps:
      - name: Bước 1 – Lấy source code
        uses: actions/checkout@v5   #Clone code về máy ảo

      - name: Bước 2 – Cài Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '18'   #Chọn version Node

      - name: Bước 3 – Cài dependencies
        run: npm install   #Cài thư viện

      - name: Bước 4 – Build project
        run: npm run build   #Build project

      - name: Bước 5 – Kiểm tra thành công
        run: echo "Build thành công!"   #Thông báo
